export const SET_BUSINESS_TYPES_LIST = 'SET_BUSINESS_TYPES_LIST';
export const FETCH_BUSINESS_TYPES_LIST_FAILED = 'FETCH_BUSINESS_TYPES_LIST_FAILED';

export const SET_SERVICES_LIST= "SET_SERVICES_LIST";

export const SET_BUSINESS_LIST = "SET_BUSINESS_LIST";