export const SET_BUSINESS_TYPES_LIST = "SET_BUSINESS_TYPES_LIST";
export const FETCH_BUSINESS_TYPES_LIST_FAILED =
  "FETCH_BUSINESS_TYPES_LIST_FAILED";

export const SET_SERVICES_LIST = "SET_SERVICES_LIST";
export const FETCH_SERVICES_LIST_FAILED = "FETCH_SERVICES_LIST_FAILED";

export const SET_BUSINESS_LIST = "SET_BUSINESS_LIST";
export const FETCH_BUSINESS_LIST_FAILED = "FETCH_BUSINESS_LIST_FAILED";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";



