export const SET_BUSINESS_TYPES_LIST = "SET_BUSINESS_TYPES_LIST";
export const FETCH_BUSINESS_TYPES_LIST_FAILED =
  "FETCH_BUSINESS_TYPES_LIST_FAILED";

export const SET_SERVICES_LIST = "SET_SERVICES_LIST";
export const FETCH_SERVICES_LIST_FAILED = "FETCH_SERVICES_LIST_FAILED";

export const SET_BUSINESS_LIST = "SET_BUSINESS_LIST";
export const FETCH_BUSINESS_LIST_FAILED = "FETCH_BUSINESS_LIST_FAILED";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_ERROR_CLEAR = "AUTH_ERROR_CLEAR";

export const INIT_USER_PROFILE="INIT_USER_PROFILE"
export const SET_USER_PROFILE_SUCCESS="SET_USER_PROFILE_SUCCESS"
export const FETCH_USER_PROFILE_FAILED="FETCH_USER_PROFILE_FAILED"

export const SEARCH_BY_SERVICE_NAME_START = "SEARCH_BY_SERVICE_NAME_START";
export const SEARCH_BY_SERVICE_NAME_SUCCESS = "SEARCH_BY_SERVICE_NAME_SUCCESS"
export const SEARCH_BY_SERVICE_NAME_FAILED="SEARCH_BY_SERVICE_NAME_FAILED";

export const SEARCH_BY_BUSINESSTYPE_NAME_START = "SEARCH_BY_BUSINESSTYPE_NAME_START";
export const SEARCH_BY_BUSINESSTYPE_NAME_SUCCESS = "SEARCH_BY_BUSINESSTYPE_NAME_SUCCESS";
export const SEARCH_BY_BUSINESSTYPE_NAME_FAILED = "SEARCH_BY_BUSINESSTYPE_NAME_FAILED";

export const SEARCH_BY_BUSINESS_NAME_START = "SEARCH_BY_BUSINESS_NAME_START"
export const SEARCH_BY_BUSINESS_NAME_SUCCESS = "SEARCH_BY_BUSINESS_NAME_SUCCESS"
export const SEARCH_BY_BUSINESS_NAME_FAILED = "SEARCH_BY_BUSINESS_NAME_FAILED"

export const  FETCH_BUSINESS_APPOINTMENT_SCHEDULE_START = "FETCH_BUSINESS_APPOINTMENT_SCHEDULE_START";
export const  FETCH_BUSINESS_APPOINTMENT_SCHEDULE_SUCCESS = "FETCH_BUSINESS_APPOINTMENT_SCHEDULE_SUCCESS";
export const FETCH_BUSINESS_APPOINTMENT_SCHEDULE_FAILED = "FETCH_BUSINESS_APPOINTMENT_SCHEDULE_FAILED";

export const SCHEDULE_APPOINTMENT_START="SCHEDULE_APPOINTMENT_START"
export const SCHEDULE_APPOINTMENT_SUCCESS="SCHEDULE_APPOINTMENT_SUCCESS"
export const SCHEDULE_APPOINTMENT_FAILED="SCHEDULE_APPOINTMENT_FAILED"

export const FETCH_BUSINESS_EMPLOYEELIST_START = "FETCH_BUSINESS_EMPLOYEELIST_START"
export const FETCH_BUSINESS_EMPLOYEELIST_SUCCESS = "FETCH_BUSINESS_EMPLOYEELIST_SUCCESS"
export const FETCH_BUSINESS_EMPLOYEELIST_FAILED = "FETCH_BUSINESS_EMPLOYEELIST_FAILED"

export const FETCH_EMPLOYEE_PROVIDING_SERVICE_LIST_START = "FETCH_EMPLOYEE_PROVIDING_SERVICE_LIST_START"
export const FETCH_EMPLOYEE_PROVIDING_SERVICE_LIST_SUCCESS = "FETCH_EMPLOYEE_PROVIDING_SERVICE_LIST_SUCCESS"
export const FETCH_EMPLOYEE_PROVIDING_SERVICE_LIST_FAILED = "FETCH_EMPLOYEE_PROVIDING_SERVICE_LIST_FAILED"